### ISSUE TITLE
502 Bad Gateway - html5.validator.nu is down!

### ISSUE THREAD

**Issue by bittner** [mozilla/html5-lint#22]
https://html5.validator.nu seems to be down since yesterday.

The script can't perform any tests, and reports `502 Bad Gateway`.

**Comment by bittner** [comment]
Anyone reading this and looking for an offline solution:

Try one of the tools listed on [validator.github.io](https://validator.github.io/validator/), e.g the Python-powered [html5validator](https://pypi.python.org/pypi/html5validator):

* Install: ``pip install html5validator``
* Validate: e.g. ``html5validator --root _build/``

Pretty awesome!

**Comment by hsivonen** [comment]
Fixed.

**Comment by thomas658** [comment]
down again since 2015-12-07

**Comment by hsivonen** [comment]
> down again since 2015-12-07

Thanks. It was broken in a different way this time. Fixed.

**Comment by thomas658** [comment]
down again on 2016-01-13

**Comment by esetnik** [comment]
down again 2016-02-24

**Comment by nickensoul** [comment]
502 again on 2016-03-18

**Comment by mattspaulding** [comment]
Down again.

**Comment by hsivonen** [comment]
Fixed. Thanks.

**Comment by Ragers** [comment]
Getting 500 Internal server error from https://html5.validator.nu/ when trying to upload HTML file

**Comment by hsivonen** [comment]
> Getting 500 Internal server error from https://html5.validator.nu/ when trying to upload HTML file

It appears that the watchdog script has revived the service successfully.

**Comment by Ragers** [comment]
I can confirm that it still gives me the exact same issue. There is something wrong when you use the linter npm module. Logging the errors I can see it gives me a 500 Internal Server error. Then go to the actual site, upload the same file I tried to test via the npm module and I also get a 500 Internal Server error. My tests use to run fine for months now, this recently became a problem.

**Comment by hsivonen** [comment]
OK. Problem confirmed. I'll take a closer look.

**Comment by hsivonen** [comment]
This has been resolved. I learned something new (and unfortunate) about nginx today: Proxying POST seems to touch the disk.

**Comment by Ragers** [comment]
Thanks @hsivonen, I can confirm it does work now. Don't we all learn something new everyday in the dev world. :)

**Comment by aduta** [comment]
Down again today - 21/12/2018

502 Bad Gateway - nginx/1.15.7
