### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by cancerberoSgx** [mozilla/html5-lint#23]
I know this is probably not an issue of this project but I'm getting 502 Bad Gateway Error using the default HTML5 validator https://html5.validator.nu/

Can you tell me where I can report this issue or provide a list of alternative links. 

Thanks and very useful project !

**Comment by cancerberoSgx** [comment]
OK, I just fixed it by using this other service https://validator.w3.org/nu/': 

html5Lint(html, {service: 'https://validator.w3.org/nu/'}, function(err, results) 

Is not an issue at all. Nevertheless it would be nice to have a list of service urls so we can alternate while one is down. Thanks and sorry for the trouble

**Comment by bittner** [comment]
You should better be using an offline solution if that's feasible for you. Look at [issue #22](https://github.com/mozilla/html5-lint/issues/22#issuecomment-152479772).
